services:
  api:
    build:
      context: juggle/
    ports:
      - "5000:80" # Expose SQL Server port to the host
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest # Use the latest SQL Server 2019 image
    container_name: sql_server_container # Choose a name for the container
    restart: unless-stopped
    environment:
      MSSQL_SA_PASSWORD: YourStrongPassword123! # Set your desired SA password here
      ACCEPT_EULA: Y # Accept the End-User License Agreement
    ports:
      - "1433:1433" # Expose SQL Server port to the host
    volumes:
      - ./data:/var/opt/mssql/data
